name: CI - Test and Quality Checks

on:
  pull_request:
    branches: [ day1, main ]
  push:
    branches: [ day1, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Lint code
      run: npm run lint || echo "Linting not configured"
      
    - name: Run unit tests
      run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
      
    - name: Build application
      run: npm run build:prod
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: matrix.node-version == 18
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  build-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check bundle size
      run: |
        npm run build:prod
        echo "📦 Bundle Analysis:"
        ls -lh dist/eliza_fruit_website/browser/
        echo "🎯 Target: < 100kB gzipped"
        
    - name: Security audit
      run: npm audit --audit-level moderate
      
    - name: Check for outdated dependencies
      run: npm outdated || true