name: CI - Test and Quality Checks

on:
  pull_request:
    branches: [ day1, main ]
  push:
    branches: [ day1, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci || npm install
      
    - name: Lint code
      run: npm run lint || echo "Linting not configured - skipping"
      
    - name: Run tests
      run: npm run test:ci
      
    - name: Build application
      run: npm run build:prod

  build-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci || npm install
      
    - name: Check bundle size
      run: |
        npm run build:prod
        echo "📦 Bundle Analysis:"
        ls -lh dist/eliza_fruit_website/ || echo "No dist directory found"
        echo "🎯 Target: < 100kB gzipped"
        
    - name: Security audit
      run: npm audit --audit-level moderate
      
    - name: Check for outdated dependencies
      run: npm outdated || true