name: Auto-Deploy to Webiste Repository

on:
  push:
    branches: [ day1, main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm run test:ci || echo "Tests not configured, skipping..."
      
    - name: Build Angular app for webiste
      run: npm run build:prod -- --base-href="/"
      
    - name: Add Docker files
      run: |
        cd dist/eliza_fruit_website
        if [ -d "browser" ]; then
          mv browser/* .
          rmdir browser
        fi
        touch .nojekyll
        cp ../../webiste-dockerfile ./Dockerfile
        cp ../../webiste-nginx.conf ./nginx.conf
      
    - name: Deploy to webiste repository
      run: |
        cd dist/eliza_fruit_website
        git init
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/mateuszczerniakowski/webiste.git
        git add .
        git commit -m "Auto-deploy: $(date '+%Y-%m-%d %H:%M:%S') - Optimized build with Docker support"
        git branch -M main
        git push -f origin main

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: github.ref == 'refs/heads/day1'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/eliza-fruit-website
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha
          latest
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max